### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by bedeho** [w3f/polkadot-re-spec#10]
1. This refers to the Polkadot Runtime Environment, but much of this appears to apply to the runtime environment in any Substrate node, is this correct? if not, in what way is it not?

2. How much is left before this should be considered complete?

**Comment by drskalman** [comment]
> This refers to the Polkadot Runtime Environment, but much of this appears to apply to the runtime environment in any Substrate node

Substrate (bar the SRML part) is the rust implementation of Polkadot Runtime Environment. 

> How much is left before this should be considered complete?

It is a work in progress and grows and changes as the Polkadot design evolves. By covering the network messages on which we are working, it should be fairly representative of current state of Polkadot RE.
