### ISSUE TITLE
SCALE Encoding Circular Definition

### ISSUE THREAD

**Issue by ansermino** [w3f/polkadot-re-spec#6]
It seems the definition of `n` in the SCALE codec is circular -- `n` is being used to define `n`:

![screenshot_2019-02-07_12-18-25](https://user-images.githubusercontent.com/14164624/52429680-88e94b00-2ad2-11e9-81bc-a1ab1e33916a.png)

Pending other potential issues in the SCALE definition its hard to discern what this is actually trying to say, I wonder if its just a case of variable name reuse?

**Comment by drskalman** [comment]
:-/ this is defining from other side, the right hand sides are being defined by the left hand side. Which is unconventional. I'll find a way of making it read better.

![image](https://user-images.githubusercontent.com/35698397/52572114-12579080-2de5-11e9-91e7-ce74f870711c.png)

Something like this but less horrible.

![image](https://user-images.githubusercontent.com/35698397/52572371-a88bb680-2de5-11e9-945b-4edd4f7cd326.png)

**Comment by ansermino** [comment]
Okay, great. If I think of a better syntax I will be sure to pass it along.

One following question -- `m` is defined using `l`, do we assume `l` to be the least significant byte of `n`?

![screenshot_2019-02-11_11-01-39](https://user-images.githubusercontent.com/14164624/52575620-83e70d00-2dec-11e9-9169-1be64a5595a9.png)

**Comment by drskalman** [comment]
Those actually should be k_x^y and we reversing side of definition notation is looks like this:
 
![image](https://user-images.githubusercontent.com/35698397/52578287-f0b0d600-2df1-11e9-85fd-0caa1d9b5946.png)

**Comment by ansermino** [comment]
Thus to get `m` we add 4 to the value denoted by the upper 6 bits? eg. `k_1 = 11111111` would produce `m = 1000011`?

**Comment by drskalman** [comment]
I think so. 

Here is the code:
https://github.com/paritytech/parity-codec/blob/master/src/codec.rs#L424  

So

drop the two first bits

11111100

move to two less significant position

111111

add 4

1000011 = 67
