### ISSUE TITLE
SCALE undefined parameters

### ISSUE THREAD

**Issue by noot** [w3f/polkadot-re-spec#7]
In the definition of the SCALE codec,  we only have i_1, j_1, and k_1 defined.

![scale1](https://user-images.githubusercontent.com/36753753/52433531-48da9600-2adb-11e9-9553-1896b79e4044.png)
![scale2](https://user-images.githubusercontent.com/36753753/52433533-4a0bc300-2adb-11e9-8691-4834b53ffa72.png)

It doesn't appear the other values i_x, j_x and k_x where x >= 2 are defined anywhere.  Do they refer to the encoding of the length n?

**Comment by drskalman** [comment]
hmm, aren't these defining the bits of of i_x, j_x and k_x?
![image](https://user-images.githubusercontent.com/35698397/52571764-4088a080-2de4-11e9-901e-43a791ee81b2.png)

**Comment by noot** [comment]
@drskalman yep, that makes sense upon further inspection.  regarding the line defining j, should it start from j_3 not j_4?

**Comment by drskalman** [comment]
Strongly related to Issue #6
