### ISSUE TITLE
Simplifying the state trie spec

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-re-spec#8]
The polkadot/substrate trie spec is the same as the Ethereum implementation besides the fact that it uses SCALE codec instead of RLP. The spec deviates from the radix-16 trie by introducing keyless branch nodes and valueless extension nodes. Extension nodes are being created whenever there is a need for a keyed branch node. 
    
In contrast to a mainstream implementation of radix trie branch, nodes can have a key and an optional value:
    
https://cs.stackexchange.com/questions/63048/what-is-the-difference-between-radix-trees-and-patricia-tries/63060#63060
        
The reason for having extension nodes is stated as follows in the Ethereum yellow paper: 
    
"Unlike a radix tree, in the case of multiple keys sharing the same prefix or in the case of a simple key having a unique suffix, two optimising nodes are provided. Thus while traversing, one may potentially acquire multiple nibbles from each of the other two node types, extension and leaf."
    
While the exact optimization that the text refers to is not clear, it seems that the optimization happens in case of "multiple successive branchings." In the Ethereum trie language it is when a branch node child is the child of another branch node, similar to to the relation
of $B_{k_1...k_n}$ and $B_{k_1...k_n0}$ but not $B_{k_1...k_n}$ and
$B_{k_1...k_n1D}$ in following tree:

![image](https://user-images.githubusercontent.com/35698397/54768848-79cbe180-4bd6-11e9-9b3a-57f0bc3259b4.png)

It is possible to include similar optimizations in the implementation, including the one in the spec that makes any application of the trie much more complicated compared to a simpls branch and leaf node trie. For example, during lookup, insertion and deletion, one always needs to check which three types of nodes are traversing, inserting and deleting, How many nodes they need to insert, delete or change the type to keep the trie consistent with the spec. This "overcomplication" has been pointed out by other implementors, as you can see here:

https://ethereum.stackexchange.com/questions/57486/why-merkle-patricia-trie-has-three-types-of-nodes

Additionally, it can be observed in the rust trie implementation:

https://github.com/paritytech/trie/blob/909b921151ebedf34456246dde0c7c4c3d3dcecb/trie-db/src/triedbmut.rs#L447

During the 2018 September Parity Retreat, @gavofyork and @arkpar stated a favourable opinion (or at least no objection) about simplifying the trie spec by removing extension nodes and using keyed branch nodes.

This discussion/conversation brought up the question of how much this optimization makes a difference in practice. To answer these questions, we have minimally modified the Ethereum trie to support the keyed branch node and compared its performance with the original Ethereum trie:

https://github.com/w3f/parity/commit/9dced6d3f89d6d7333d2b1c9e0e0e823511c759a

Using @arkpar trie bench marking implementation, we inserted 1000*10000 (key, values) in each trie where each value is a byte array of 64-byte length.

Here is the comparison result:

    Trie with Branch and Leaf nodes (first run, second run):

    Total trie size:
    2,061,059,350 bytes in 35 selected items, 1,852,973,127 bytes in 32
selected items
    
    Time to generate :
    
    real        14m55.902s, 10m52.623s
    user        19m48.892s, 13m19.568s
    sys         3m13.931s,  2m23.252s
    
    Trie with branch, extension and leaf nodes (first run, second run):
    Total trie size:
    1,968,010,923 bytes in 33 selected items, 1,746,310,353 bytes in 30 selected items
    
    Time to generate
    
    real        15m3.891s, 11m11.950s
    user       20m1.631s, 13m50.667s
    sys      3m14.510s, 2m22.004s

In both cases, a simple trie is being generated slightly faster while occupying marginally more space (around 5%). Note that it represents an unoptimized implementation to try to deviate the least from the original Ethereum implementation. Otherwise, there is plenty of space for optimization. 

Given the complexity that the extension nodes add to the spec compared to the %5 space optimization, and given that a similar optimization can be achieved during the implementation, we propose to simplify the polkadot state trie spec, similarly to the spec explained in Section 5:

https://github.com/w3f/polkadot-re-spec/blob/substrate_trie_vs_simpler_trie/polkadot_re_spec_alternative_simpler_trie.pdf

Here is a diff of specs:

https://github.com/w3f/polkadot-re-spec/blob/substrate_trie_vs_simpler_trie/polkadot_re_spec_alternative_simpler_trie_compared_with_original.pdf

The spec is just an example of how minimally we can modify the current trie to get a simpler extension-less trie. Another simplification is desirable to the HPE when we do not have extension nodes.

**Comment by arkpar** [comment]
Looks like a few bytes could be saved by encoding empty partial brach keys into `NodePrefix`. E.g.
```
1     N is a leafnode
128   N is a branch node without value and empty partial key
129   N is a branch node with value  and empty partial key
254   N is a branch node without value and partial key
255   N is a branch node with value and partial key
```

**Comment by drskalman** [comment]
I agree with @arkpar and with that the trie will be more efficient also in space than the current one. 

But I also say the nodeprefix shouldn't be used to compute the Merkle hash for the merkle proof (the hash function should only be applied to hash of children and the nodes possible value). This is because with a proof that doesn't contains the nodeprefix you still can guarantee the integrity of the same data.

**Comment by cheme** [comment]
- I do not really follow the encoding discussed above, for me `NodeHeader` encoding would be:
```
0     N is a empty trie 
1     N is a leafnode with empty partial key
2-86 variant with partial key size from 1 to 85
87    N is a branch node without value and empty partial key
88-172 variant with nibble size from 1 to 84
172   N is a branch node with value  and empty partial key
172-255 variant with nibble size from 1 to 84
```
this makes max nibble length 85 and conflicts with current double storage key size in substrate (twox128 hash cat with blake256 for max nibble size of (16 + 32)*2= 96).

From the specs, and if we force the api to only use key/value with key being nibble of even size (byte array), we can also do:
```
0     N is a empty trie 
1     N is a leafnode with empty partial key
2-50 variant with partial key half size from 1 to 48 (since only even value are allowed)
51    N is a branch node without value and empty partial key
52-147 variant with nibble size from 1 to 96
148   N is a branch node with value  and empty partial key
149-244 variant with nibble size from 1 to 96
253   leaf Extended encoding: TODO define a way to encode infini size in next bytes
253   leaf Extended encoding odd: TODO define a way to encode infini size in next bytes
254   branch without value Extended encoding: TODO infini size next bytes 
255   branch with value Extended encoding: TODO infini size next bytes 
```
*there may be some offset error but it seems to fit anyway*
That is if we absolutely want the one byte encoding (for common case). More traditional bitmask design could be use if we allow less compact encoding.

Warning for extended encoding it must be an offset (size = max_enc_size_onebyte + encoded_size_byte), to avoid malleability.
I would rather not use Substrate compact encoding for the same reason: an encoding scheme that map exactly one encoding to one value and one value to one encoding.

I like the idea to allow unbounded key length even if practically it is useless.

- I also like the idea to remove nodeprefix from the root hash, I think it can work for removing branch nibble length (it is redundant with the trie structure) , but for other case (removing variant def and leaf nible len) I can imagine some state where you got same trie root for different content.
Also the implementation could be tricky/costy for the case of branch including there child (child encoded len < 32).

**Comment by drskalman** [comment]
The the pull request corresponding to the @cheme's spec is here:

 https://github.com/paritytech/trie/pull/11

The value of not include the node prefix in the hash is that you can update the prefix encoding without breaking all the chains.

I'm bit confused about the complication of node header description. In the sense that both leaf and branch nodes can be keyless. so we have 
 
- bit x showing if the node has key or not.

and we have 

- bit y,z which indicates one of these 4:
 
- empty node
- leaf node
- branch node with value
- branch node without value  
 
Isn't that simpler?

**Comment by drskalman** [comment]
@cheme could you explain this? 

"Also the implementation could be tricky/costy for the case of branch including there child (child encoded len < 32)."

We can drop the prefix before hashing and if it is short we just won't hash it.

**Comment by cheme** [comment]
* The `NodeHeader` is actually a single byte containing both node type and node nibble length (for type with a prefix). So 3 bit for encoding type lets only 5 bit for encoding length: so 32 for max number of nibble (currently using ranges allows a better compaction). I agree that bitmask for encoding is simpler, I do not know if we need to stick to this single byte encoding constraint.
* If we skip the `NodeHeader` in the hash, I think we can have situation where the trie root is the same for different contents, eg
  - trie with single key/val ([0],[1,1,1]) root is hash of [0,3,1,1,1]
  - trie with single key/val ([0,3,1],[1]) root is hash of [0,3,1,1,1]
 (with content encoded by simply prepending a single byte for len).
* for branch that include directly node content(s) instead of hash (len of child node content < 32) we need to calculate hash over the branch encoded without its `NodeHeader` at position 0 , but also without the `NodeHeader` of the included content(s) at some not statically defined position(s). So basically we need two encoding function for branch (one for data inclusion and one for hash). There is also the case where we have more than one level of direct inclusion: branch containing branch containing .... containing leaf, the depth being limited by the 31 byte len.

> We can drop the prefix before hashing and if it is short we just won't hash it.

Yes but we would still need to do the encoding for data with all prefix.

**Comment by drskalman** [comment]
> I do not know if we need to stick to this single byte encoding constraint.

I found this in the code, so it seems to be two bytes not one byte:

  	// We use two ranges of possible values; one for leafs and the other for extensions.
	// Each range encodes zero following nibbles up to some maximum. If the maximum is
	// reached, then it is considered "big" and a second byte follows it in order to
	// encode a further offset to the number of nibbles of up to 255. Beyond that, we
	// cannot encode. This shouldn't be a problem though since that allows for keys of
	// up to 380 nibbles (190 bytes) and we expect key sizes to be generally 128-bit (16
	// bytes) or, at a push, 384-bit (48 bytes).

> So 3 bit for encoding type lets only 5 bit for encoding length: so 32 for max number of nibble (currently using ranges allows a better compaction).

So I wasn't able to count exactly how many extra bit the non-masking encoding is giving us

but, from information theoritic point of view, 

- you need to know if a node is leaf or branch that is one bit of information.
- you also need to know if the node has a key or not and the fact that it is branch or not doesn't give you any information about it having a key or not so that's another bit.

So you have at most 6 bits left for the length. 

And then the branch, having key or not having key is also independent of the fact that it has value or not, so for the branch you can only have 5 free bits.
  
so our saving is only one bit for the leaf node case, as far as I understand. It also doesn't mean that we can only have 32 nibbles, it means for 32 nibles or longer we need to use an extra bytes.

I personally not sure if that one bit is worth saving considering making the spec considerably simpler. However if we are insisting on saving that one bit, given that we need less bits for the merkle proof, transforming the current prefix+len -> len only byte without touching the rest of the bytes should be easy. 
> If we skip the NodeHeader in the hash, I think we can have situation where the trie root is the same for different contents

I agree we shouldn't lose informations critical to authenticity of the trie including the key length. That would be a security vulnerability. I didn't mean dropping the information about the key length.

**Comment by drskalman** [comment]
Another question about @arkpar  and @cheme's prefix is that because we store the key length, why do we also need to have also an indicator showing if the node has key or not? if the length is 0 then the node doesn't have key. Doesn't it make sense?

**Comment by drskalman** [comment]
This spec is the result of my meeting with @cheme, this is the new structure for the Merkle value of a node. It is pending @arkpar 's assent. Specifically the use of mask value for node type instead of range value and padding the odd lengthed partial key at the end (instead of at the beginning) which we thinks is simpler to implement:

The Merkle value of the node is either following byte array or its hash if it consists of more than 32 Bytes:
   
     |-------------+--------------------------+-------------+-------|
     | NodeHearder | Extra partial key length | Partial Key | Value |
     |-------------+--------------------------+-------------+-------|

# NodeHeader

NodeHearder is as follows:
   
     |------------+---------------------------|
     | NodePrefix | 6 bits Partial key length | 
     |------------+---------------------------|

Where NodePrefix is stored in the most significant bits of NodeHeader:

00: Special Value (empty trie etc)
01: Leaf Node 
10: Branch Node without value
11: Branch Node without value
   
The 6 less significant bit is used to store the length of partial key shared by the node and its descendants number of nibbles.

# Extra partial key length

If the partial key consists of more than 62 nibbles then we set these values to 63 and store the the partial key length - 63 in the following bytes. using this algorithm:
   
    l = partial_key - 63
    i = 0
    while (true):
      if l < 255:
        extra_key_length[i] = l
        break
      else:
        extra_key_length[i] = 255
        l = l - extra_key_length
        i = i + 1

Note that practically we don't expect the length of a partial key is more than 317 but we do not want the spec to limit the partial key length. So we don't worry about the fact that it is not optimal.

# Partial Key

If partial key length is even equals to 2k

     |-------------------------------------+-----+-------------------------------------------|
     | Partial key[1] Partial key Nible[0] | ... | Partial key[2k-1] Partial key Nible[2k-2] |
     |-------------------------------------+-----+-------------------------------------------|


If partial key length is odd equals to 2k + 1

     |-------------------------------------+-----+----------------------|
     | Partial key[1] Partial key Nible[0] | ... | 0000 Partial key[2k]  |
     |-------------------------------------+-----+----------------------|

# Value

For the Leaf node, the nodes value is encoded using SCALE codec.

For branch node it is as follows

     |-----------------+-----------------+-----------------+-----+-----------------+-------------------|
     | Children Bitmap | Enc(Child[i_1]) | Enc(Child[i_2]) | ... | Enc(Child[i_n]) | Branch Node Value |
     |-----------------+-----------------+-----------------+-----+-----------------+-------------------|

Children bitmap:
   
     |-------------------------+-------------------------|
     | Children Bitmap Byte[0] | Children Bitmap Byte[1] |
     |-------------------------+-------------------------|

Each bits counted using little endian, each is set if the branch has a child with sharing the index as in its key.

Branch node value SCALE Encoded if Branch has value.
   
Enc(Child[i_j]) is the scale encoded value of the Merkle value of Child[i_j] node.

The Merkle value of the node, is defined recursively using this definition.

**Comment by arkpar** [comment]
lgtm

**Comment by cheme** [comment]
I am implementing the new scheme (changing the padding position was more tricky than I thought), and got a few new feedbacks:

- I put a pretty low (max u16) limit size for nibble/prefix length, because I feared unlimited size could be a dos vector. Thinking twice the biggest risk is to call encode over a big size and exhaust resources but a big size implies a bigger key (that is also true for the reading part). I may change it to be u32 meaning it is no longer a upper bound but a technical definition of a size.
At this point I encode bigger values to the max value without an error (the application should catch error for big key on its own, the trie implementation says that both are the same key), might not be super smart.

- I also did modify a bit the encoding of size so that for byte > 1.
  - when the added size to the value was:
    0 to 254 and 255 cut to 254 (but also indication a value in next byte)
  - I changed it to
    the same thing but adding one (resuling in 1 to 255) see https://github.com/cheme/trie/blob/57a86c5c133514c3ea1a4aaeee4436201f10919b/test-support/reference-trie/src/lib.rs#L345  `s_encode_size_prefix` and `s_decode_size`
  - another possible encoding would be:
    1 to 255 and 0 rounded to 255 (but also indicating a value in next byte)

   that is to avoid being able to encode 0 on a next byte and get two valid encoding of a same value

- also while implementing, I started to wonder if targeting other layout of trie could be usefull (I did start putting some pre code for that : https://github.com/cheme/trie/blob/57a86c5c133514c3ea1a4aaeee4436201f10919b/trie-db/src/nibbleslice.rs#L106). This really as a second step but I feel the code could benefit from being generalized this way (first step with upper bound of one byte and no unaligned case makes it only 4 variant).

-  I currently kept `Compact<u32>` for encode/decode the value length of the array, I inferred SCALE was Substrate Compact Array Linear Encoding (really not sure about the linear)? I do not know if `Compact<u32>` is simple enough, just mentioning it as we did not talk about it (would require https://github.com/paritytech/parity-codec/pull/67 in my opinion).

**Comment by noot** [comment]
Hey, what is the correct prefix for branch with and without value? right now it says
```
00: Special Value (empty trie etc)
01: Leaf Node
10: Branch Node without value
11: Branch Node without value
```

**Comment by noot** [comment]
> # Partial Key
> If partial key length is even equals to 2k
> 
> ```
>  |-------------------------------------+-----+-------------------------------------------|
>  | Partial key[1] Partial key Nible[0] | ... | Partial key[2k-1] Partial key Nible[2k-2] |
>  |-------------------------------------+-----+-------------------------------------------|
> ```
> If partial key length is odd equals to 2k + 1
> 
> ```
>  |-------------------------------------+-----+----------------------|
>  | Partial key[1] Partial key Nible[0] | ... | 0000 Partial key[2k]  |
>  |-------------------------------------+-----+----------------------|
> ```

Could you also clarify this? Partial key I'm assuming here is a series of nibbles, say with length 2k (and is even). So is this saying we order the nibbles back into bytes in little endian, so the encoded partial key now has length k?

**Comment by cheme** [comment]
@noot Indeed one of 10 or 11 should be branch without value, when implementing I did not see it (reading 10 without , I filled 11).
Current substrate impl uses 254 `without` and 255 `with` so using 11 for with would be more consistent. 
On partial key, that is indeed little endian encoding of 4 bit nibble with two ordered nibble per bytes (little endian reverse ordering per byte on the ascii description). When you got odd number of 4 bit nibble, the last nibble is filled with `0000` (other value should be considered invalid).
(this change from the previous implementation where the padding was at start).

**Comment by noot** [comment]
@cheme thanks so much, that clarifies everything :) I'm currently working on implementing this in Go: https://github.com/ChainSafe/gossamer/tree/elizabeth/trie-encoding  I think going for 10 `without` and 11 `with` value makes sense and I'll go with that.

**Comment by drskalman** [comment]
The simplifed trie spec is now included in the spec: https://github.com/w3f/polkadot-re-spec/commit/cacadb5774b9578c9569a109a0b5587a72d8cdae
