### ISSUE TITLE
Review BABE block production spec

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-re-spec#9]
Section 7.2 Block production need to be reviewed and verified that it actually conforms with the Babe protocol. Any other suggestions or corrections are also welcome.

Its latest iteration can be found here:
https://github.com/w3f/polkadot-re-spec/blob/babe-production/polkadot_re_spec.pdf

**Comment by hndnklnc** [comment]
I have a few comments. Otherwise, it looks ok for me.

- ??? in Definition 32 should be 2^{l}\phi(\theta) where l is the length of the VRF output, phi(theta) = 1 -(1-c)^\theta and \theta = S/n (S is the total stake and n is the number of validators)
- Block time is used to define the time takes to add one block to the best chain in BABE. I think it is better to use another name.
- There are some sub-routines not explained such as 'SubChain' (there is a typo there as well) and 'Slot-Offset' and a notion such as 'last-finalized slot'.

**Comment by drskalman** [comment]
I believe I addressed most of your points. I also added the epoch randomness algorithm:

https://github.com/w3f/polkadot-re-spec/blob/master/polkadot_re_spec.pdf

Except I still can't compute SC_n.

>    ??? in Definition 32 should be 2^{l}\phi(\theta) where l is the length of the VRF output, phi(theta) = 1 -(1-c)^\theta and \theta = S/n (S is the total stake and n is the number of validators)

So base on our discussion, I gather it safe to assume that S/n=1. what value should c be set to?

> Block time is used to define the time takes to add one block to the best chain in BABE. I think it is better to use another name.

I changed it to "block arrival time".

> There are some sub-routines not explained such as 'SubChain' (there is a typo there as well) and 'Slot-Offset' and a notion such as 'last-finalized slot'.

I defined all (and dropped the last-finalized-block) based on our discussion.

**Comment by hndnklnc** [comment]
> Except I still can't compute SC_n.
>
What is SC_n?

??? in Definition 32 should be 2^{l}\phi(\theta) where l is the length of
> the VRF output, phi(theta) = 1 -(1-c)^\theta and \theta = S/n (S is the
> total stake and n is the number of validators)
>
> So base on our discussion, I gather it safe to assume that S/n=1. what
> value should c be set to?
>

Why do you need to specify 'c' value now? Can't you just say that
phi(theta) = c? I think it is better to give a concrete 'c' value later
because it needs to be decided according to the decision on network delay
resistance that we want and block time. Some values are here:
http://research.web3.foundation/en/latest/polkadot/BABE/Babe/#6-practical-results



> There are some sub-routines not explained such as 'SubChain' (there is a
> typo there as well) and 'Slot-Offset' and a notion such as 'last-finalized
> slot'.
>
> I defined all (and dropped the last-finalized-block) based on our
> discussion.
>
I could not see them in the pdf.

>

**Comment by hndnklnc** [comment]
Why do you take S/n = 1? S/n shows the relative stake of a party. The
relative stake of all validators is equal so it cannot be 1 for all parties
because if it is 1 for a validator, it means it is 0  for others.

**Comment by drskalman** [comment]
> What is SC_n?

It is the number of slots in one epoch presented by ???? in Notation 32. 

> Why do you need to specify 'c' value now? Can't you just say that
> phi(theta) = c?
Well yes and no. the spec should be in a way that a coder should be able to
turn it into a code and it should results in a consistent output across
different nodes and different implementations. So either we should give them a
concrete c or a concrete way of computing c (for example algorithm:
compute-c () based on the block time of
epoch n-2 set c equal to blah blah ...).

> I think it is better to give a concrete 'c' value
> later
I think it is better to give a concrete value now and update it later.
It is not carved in stone. It is an editable text file that I can edit
later ;-)

Unless, if we are planning to have a runtime function which calculate 'c'
based on the condition of the chain some how dynamically, which then I'll
say call that runtime function to obtain the 'c' and specify it in the
runtime later.

> I could not see them in the pdf.

I ment I defined them after you told me they are not defined :-)

many thanks :-)

**Comment by drskalman** [comment]
> relative stake of all validators is equal so it cannot be 1 for all parties because if it is 1 for a validator, it means it is 0 for others.

I thought there are no other parties for now. All block producers are validators. We can just assume there is no other node/party on the network, as much as it concerns BABE. Help me if I'm missing something.

**Comment by hndnklnc** [comment]
When I say parties, I mean validators. We cannot just assume that there is only one validator. If we assume like this, what should we assume for the relative stake of honest validators? All analysis changes in this case and I am not sure if we can have any security analysis if we assume there is only one validator. Phi defines the probability of one validator is selected as a leader and it has to be proportional to the relative stake which is S/n which is the main idea of proof of stake.

**Comment by hndnklnc** [comment]
> I think it is better to give a concrete 'c' value later
> I think it is better to give a concrete value now and update it later. It is not carved in stone. It is an editable text file that I can edit later ;-) Unless, if we are planning to have a runtime function which calculate 'c' based on the condition of the chain some how dynamically, which then I'll say call that runtime function to obtain the 'c' and specify it in the runtime later.

I have the code to compute the parameters for BABE. https://github.com/w3f/research/tree/master/parameters
Either I can write pseudo code to compute parameters and give it to you or compute concrete values for a network resistance value that makes sense for me :) You choose

**Comment by drskalman** [comment]
>  We cannot just assume that there is only one validator.

No there is 1000 validator each of them has 1/1000 of the total stakes there are 1000 shares of the total Statke. So S =1000, each validator has one share, so S/n=1000/1000=1. Tell me what I'm getting wrong here.

**Comment by drskalman** [comment]
> Either I can write pseudo code to compute parameters and give it to you or compute concrete values for a network resistance value that makes sense for me :) You choose

For now I'll Add `BabeApi_slot_duration` as a place holder. later we can specify when we are specing the run time.

**Comment by hndnklnc** [comment]
> > We cannot just assume that there is only one validator.
> 
> No there is 1000 validator each of them has 1/1000 of the total stakes there are 1000 shares of the total Statke. So S =1000, each validator has one share, so S/n=1000/1000=1. Tell me what I'm getting wrong here.

You are right for the misunderstanding. I didn't formulate what I am thinking. Forget about S/n. The correct \theta should be equal to 1/n (i.e, each validator has the stake s = S/n, relative stake of a validator (theta) s/S).

**Comment by drskalman** [comment]
Sure I think I also add **BabeApi_slot_winning_threshold** which
